version: '3.8'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/pokechallenge?schema=public
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokechallenge
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
